# No commitear datos sensibles aquí. Solo configuración de desarrollo.
version: '3.9'
 
services:

  backend:
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
 
  ai-service:
    command: npm run dev
    volumes:
      - ./ai-service:/app
      - /app/node_modules
 